server:
   port: 8080
spring:
  application:
    name: controle-estoque
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/controle-estoque
    username: postgres
    password: admin123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
security:
  jwt:
    token:
      secret-key: 53cr37
      expire-length: 3600000
